# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-28 18:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('comment', models.CharField(max_length=200)),
                ('opttime', models.DateTimeField()),
                ('optvalue', models.IntegerField()),
                ('by', models.ForeignKey(on_delete=models.SET(1), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActionTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.BooleanField()),
                ('serial', models.CharField(max_length=16)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('channeltype', models.IntegerField(choices=[(1, 'GPRS'), (2, 'GPRS + Ethernet'), (3, '\u0420\u0430\u0434\u0456\u043e'), (4, '\u041b\u0456\u043d\u0456\u044f'), (5, '\u0417\u043e\u0432\u043d\u0456\u0448\u043d\u0456\u0439 \u043a\u043e\u043c\u043c.')])),
                ('dualsim', models.BooleanField()),
                ('iscommunicator', models.BooleanField()),
                ('deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=150)),
                ('type', models.IntegerField(choices=[(1, '\u041e\u0445\u043e\u0440\u043e\u043d\u043d\u0438\u0439'), (2, '\u041f\u043e\u0436\u0435\u0436\u043d\u0438\u0439'), (3, '\u041e\u0445\u043e\u0440\u043e\u043d\u043d\u043e-\u043f\u043e\u0436\u0435\u0436\u043d\u0438\u0439'), (4, '\u041d\u0435\u043f\u0443\u043b\u044c\u0442\u043e\u0432\u0438\u0439')])),
                ('contract', models.CharField(max_length=12)),
                ('active', models.BooleanField()),
                ('deleted', models.BooleanField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ReplacedEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.IntegerField(choices=[(1, '\u0421\u043f\u043e\u0432\u0456\u0449\u0443\u0432\u0430\u0447'), (2, '\u041a\u043e\u043c\u0443\u043d\u0456\u043a\u0430\u0442\u043e\u0440'), (3, '\u041f\u0440\u0438\u043b\u0430\u0434'), (4, '\u0406\u043d\u0448\u0435')])),
                ('date', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('comment', models.CharField(max_length=200)),
                ('objectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmsmain.Object')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standalone', models.BooleanField()),
                ('taskid', models.IntegerField()),
                ('type', models.IntegerField(choices=[(1, '\u0417\u0430\u043f\u0438\u0442 \u0434\u0456\u0457'), (2, '\u0417\u0430\u043f\u0438\u0442 \u0456\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0456\u0457'), (3, '\u0417\u0430\u043f\u0438\u0442 \u0437\u0430\u0431\u0435\u0437\u043f\u0435\u0447\u0435\u043d\u043d\u044f'), (4, '\u041e\u0441\u043e\u0431\u0438\u0441\u0442\u0438\u0439 \u0437\u0430\u043f\u0438\u0442'), (5, '\u0406\u043d\u0448\u0435')])),
                ('description', models.CharField(max_length=240)),
                ('reply', models.CharField(max_length=240)),
                ('opendate', models.DateTimeField()),
                ('closedate', models.DateTimeField()),
                ('closed', models.BooleanField()),
                ('private', models.BooleanField()),
                ('by', models.ForeignKey(on_delete=models.SET(1), related_name='request_by', to=settings.AUTH_USER_MODEL)),
                ('to', models.ForeignKey(on_delete=models.SET(1), related_name='request_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('iccid', models.CharField(max_length=19)),
                ('comment', models.CharField(max_length=200)),
                ('suspended', models.BooleanField()),
                ('lost', models.BooleanField()),
                ('objectid', models.ForeignKey(on_delete=models.SET(1), to='tmsmain.Object')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventtime', models.DateTimeField()),
                ('eventtype', models.IntegerField(choices=[(1, '\u0422\u0440\u0438\u0432\u043e\u0433\u0430'), (2, '\u041d\u0435\u0441\u043f\u0440\u0430\u0432\u043d\u0456\u0441\u0442\u044c'), (3, '\u0417\u0432\u044f\u0437\u043e\u043a'), (4, '\u0417\u0430\u044f\u0432\u0430 \u0412\u041e'), (5, '\u0412\u043d\u0443\u0442\u0440\u0456\u0448\u043d\u0454 \u0437\u0430\u0432\u0434\u0430\u043d\u043d\u044f'), (6, '\u0406\u043d\u0448\u0435')])),
                ('description', models.CharField(max_length=250)),
                ('priority', models.IntegerField(choices=[(1, '\u041d\u0438\u0437\u044c\u043a\u0438\u0439'), (2, '\u0421\u0435\u0440\u0435\u0434\u043d\u0456\u0439'), (3, '\u0412\u0438\u0441\u043e\u043a\u0438\u0439'), (4, '\u041a\u0440\u0438\u0442\u0438\u0447\u043d\u0438\u0439')])),
                ('status', models.IntegerField(choices=[(1, '\u0412\u0438\u043a\u043e\u043d\u0430\u043d\u043e'), (2, '\u041e\u0447\u0456\u043a\u0443\u0454\u0442\u044c\u0441\u044f \u043f\u0456\u0434\u0442\u0432\u0435\u0440\u0434\u0436\u0435\u043d\u043d\u044f'), (3, '\u0410\u043a\u0442\u0438\u0432\u043d\u0435'), (4, '\u041e\u0447\u0456\u043a\u0443\u044e\u0442\u044c\u0441\u044f \u0434\u0456\u0457 \u0437\u0430\u043c\u043e\u0432\u043d\u0438\u043a\u0430'), (5, '\u041e\u0447\u0456\u043a\u0443\u0454\u0442\u044c\u0441\u044f \u0437\u0430\u0431\u0435\u0437\u043f\u0435\u0447\u0435\u043d\u043d\u044f'), (6, '\u0412\u0456\u0434\u0442\u0435\u0440\u043c\u0456\u043d\u043e\u0432\u0430\u043d\u043e \u0434\u043e:')])),
                ('lastactivity', models.DateTimeField()),
                ('delaytill', models.DateTimeField()),
                ('closed', models.DateTimeField()),
                ('assignedto', models.ForeignKey(on_delete=models.SET(1), related_name='task_assignedto', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=models.SET(1), related_name='task_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TempEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.IntegerField(choices=[(1, '\u0421\u043f\u043e\u0432\u0456\u0449\u0443\u0432\u0430\u0447'), (2, '\u041a\u043e\u043c\u0443\u043d\u0456\u043a\u0430\u0442\u043e\u0440'), (3, '\u041f\u0440\u0438\u043b\u0430\u0434'), (4, '\u0406\u043d\u0448\u0435')])),
                ('quantity', models.IntegerField()),
                ('comment', models.CharField(max_length=200)),
                ('objectid', models.ForeignKey(on_delete=models.SET(1), to='tmsmain.Object')),
                ('taskid', models.ForeignKey(on_delete=models.SET(1), to='tmsmain.Task')),
            ],
        ),
        migrations.CreateModel(
            name='UserEx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, '\u0410\u0434\u043c\u0456\u043d\u0456\u0441\u0442\u0440\u0430\u0442\u043e\u0440'), (2, '\u0421\u0443\u043f\u0435\u0440\u0432\u0456\u0437\u043e\u0440'), (3, '\u041e\u043f\u0435\u0440\u0430\u0442\u043e\u0440'), (4, '\u041a\u043e\u0440\u0438\u0441\u0442\u0443\u0432\u0430\u0447')])),
                ('canclose', models.BooleanField()),
                ('fired', models.BooleanField()),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.ForeignKey(on_delete=models.SET(1), to='tmsmain.TaskLabel'),
        ),
        migrations.AddField(
            model_name='task',
            name='objectid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmsmain.Object'),
        ),
        migrations.AddField(
            model_name='object',
            name='region',
            field=models.ForeignKey(on_delete=models.SET(1), to='tmsmain.Region'),
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ForeignKey(on_delete=models.SET(1), to='tmsmain.DeviceType'),
        ),
        migrations.AddField(
            model_name='action',
            name='taskid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmsmain.Task'),
        ),
        migrations.AddField(
            model_name='action',
            name='type',
            field=models.ForeignKey(on_delete=models.SET(1), to='tmsmain.ActionTypes'),
        ),
    ]
