# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-06 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsmain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='objectid',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to='tmsmain.Object'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='replacedequipment',
            name='type',
            field=models.IntegerField(choices=[(1, '\u0421\u043f\u043e\u0432\u0456\u0449\u0443\u0432\u0430\u0447'), (2, '\u0410\u043a\u0443\u043c\u0443\u043b\u044f\u0442\u043e\u0440'), (3, '\u041a\u043e\u043c\u0443\u043d\u0456\u043a\u0430\u0442\u043e\u0440'), (4, '\u041f\u0440\u0438\u043b\u0430\u0434'), (5, '\u0406\u043d\u0448\u0435')]),
        ),
        migrations.AlterField(
            model_name='tempequipment',
            name='type',
            field=models.IntegerField(choices=[(1, '\u0421\u043f\u043e\u0432\u0456\u0449\u0443\u0432\u0430\u0447'), (2, '\u0410\u043a\u0443\u043c\u0443\u043b\u044f\u0442\u043e\u0440'), (3, '\u041a\u043e\u043c\u0443\u043d\u0456\u043a\u0430\u0442\u043e\u0440'), (4, '\u041f\u0440\u0438\u043b\u0430\u0434'), (5, '\u0406\u043d\u0448\u0435')]),
        ),
    ]
