# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsmain', '0002_auto_20161106_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.IntegerField(choices=[(1, '\u0421\u043f\u043e\u0432\u0456\u0449\u0443\u0432\u0430\u0447'), (2, '\u0410\u043a\u0443\u043c\u0443\u043b\u044f\u0442\u043e\u0440'), (3, '\u041a\u043e\u043c\u0443\u043d\u0456\u043a\u0430\u0442\u043e\u0440'), (4, '\u041f\u0440\u0438\u043b\u0430\u0434'), (5, '\u0406\u043d\u0448\u0435')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='eventtype',
            field=models.IntegerField(choices=[(1, '\u0422\u0440\u0438\u0432\u043e\u0433\u0430'), (2, '\u041d\u0435\u0441\u043f\u0440\u0430\u0432\u043d\u0456\u0441\u0442\u044c'), (3, "\u0417\u0432'\u044f\u0437\u043e\u043a"), (4, '\u0417\u0430\u044f\u0432\u0430 \u0412\u041e'), (5, '\u0412\u043d\u0443\u0442\u0440\u0456\u0448\u043d\u0454 \u0437\u0430\u0432\u0434\u0430\u043d\u043d\u044f'), (6, '\u0406\u043d\u0448\u0435')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, '\u041d\u0438\u0437\u044c\u043a\u0438\u0439'), (2, '\u0417\u0432\u0438\u0447\u0430\u0439\u043d\u0438\u0439'), (3, '\u0412\u0438\u0441\u043e\u043a\u0438\u0439'), (4, '\u041a\u0440\u0438\u0442\u0438\u0447\u043d\u0438\u0439')]),
        ),
        migrations.DeleteModel(
            name='ActionTypes',
        ),
    ]
