# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 01:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsmain', '0004_auto_20161119_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='opened',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 2, 1, 5, 37, 7698)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='eventtype',
            field=models.IntegerField(choices=[(1, '\u0425\u0438\u0431\u043d\u0430 \u043f\u043e\u0434\u0456\u044f'), (2, '\u041d\u0435\u0441\u043f\u0440\u0430\u0432\u043d\u0456\u0441\u0442\u044c'), (3, "\u0417\u0432'\u044f\u0437\u043e\u043a"), (4, '\u0417\u0430\u044f\u0432\u0430 \u0437\u0430\u043c\u043e\u0432\u043d\u0438\u043a\u0430'), (5, '\u0412\u043d\u0443\u0442\u0440\u0456\u0448\u043d\u0454 \u0437\u0430\u0432\u0434\u0430\u043d\u043d\u044f'), (6, '\u0406\u043d\u0448\u0435')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, '\u0410\u043a\u0442\u0438\u0432\u043d\u0435'), (2, '\u041e\u0447\u0456\u043a\u0443\u0454\u0442\u044c\u0441\u044f \u043f\u0456\u0434\u0442\u0432\u0435\u0440\u0434\u0436\u0435\u043d\u043d\u044f'), (3, '\u0412\u0456\u0434\u0442\u0435\u0440\u043c\u0456\u043d. \u0434\u043e:'), (4, '\u041e\u0447\u0456\u043a\u0443\u044e\u0442\u044c\u0441\u044f \u0434\u0456\u0457 \u0437\u0430\u043c\u043e\u0432\u043d\u0438\u043a\u0430'), (5, '\u041e\u0447\u0456\u043a\u0443\u0454\u0442\u044c\u0441\u044f \u0437\u0430\u0431\u0435\u0437\u043f\u0435\u0447\u0435\u043d\u043d\u044f'), (6, '\u0412\u0438\u043a\u043e\u043d\u0430\u043d\u043e')]),
        ),
    ]
